
--Inventory level categorization--

SELECT Product_type , Availability ,
CASE
    WHEN Availability < 25 THEN 'Low_stock'
    WHEN Availability > 60 THEN 'Overstocked'
    ELSE 'Well_stocked' End AS Inventory_Level_Categorization
    FROM [Supply chain analytics]


--Product type with the highest revenue--

SELECT TOP 1 Product_type , SUM(Revenue_generated) AS total_revenue
FROM [Supply chain analytics]
GROUP BY Product_type
ORDER BY total_revenue DESC


--Top 5 Best selling sku--

SELECT TOP 5  SKU ,SUM(Number_of_products_sold) AS total_unit_Sold ,
ROW_NUMBER()  OVER(ORDER BY SUM(Number_of_products_sold) DESC) AS [TOP]
FROM [Supply chain analytics]
GROUP BY SKU


-- route with lowest average shipping cost--

SELECT TOP 1 AVG(Shipping_costs)  AS Avg_shipping_cost, Routes
FROM [Supply chain analytics]
GROUP BY Routes
ORDER BY Avg_shipping_cost ASC


--top 3 locations with highest order quantity--

SELECT TOP 3 Location , SUM(Order_quantities) AS total_quantity ,
ROW_NUMBER() OVER (ORDER BY SUM(Order_quantities) DESC) AS [TOP]
FROM [Supply chain analytics]
GROUP BY Location


-- most product type sold--

SELECT TOP 1 SUM(Number_of_products_sold) AS total_product_sold,  Product_type 
FROM [Supply chain analytics]
GROUP BY Product_type
ORDER BY total_product_sold DESC


--how many product pass , fail or pending--

SELECT Inspection_results ,
COUNT(*) As Total_product
FROM  [Supply chain analytics]
GROUP BY Inspection_results


--Supplier with the fastest manufacturing lead time--

SELECT TOP 1 Supplier_name , SUM(Manufacturing_lead_time) AS Manufacturing_lead_time
FROM [Supply chain analytics]
GROUP BY Supplier_name
ORDER BY Manufacturing_lead_time ASC
 

-- SKUs with revenue higher than average--

SELECT SKU , Revenue_generated
FROM [Supply chain analytics]
WHERE Revenue_generated > (SELECT AVG(Revenue_generated) FROM [Supply chain analytics])


--all item purchased by each gender--

SELECT Price , Number_of_products_sold , Customer_Gender ,
 SUM(Price) OVER(PARTITION BY Customer_Gender ) AS total_price_by_Gender
 FROM [Supply chain analytics]


 --Revenue generated by each carriers Descending--

 ;WITH RevCTE AS
 (
   SELECT SKU ,  Lead_time , Location , Shipping_carriers , SUM(Revenue_generated)
   OVER(PARTITION BY Shipping_carriers) AS Revenue
   FROM [Supply chain analytics]
  )
 SELECT SKU ,  Lead_time , Location , Shipping_carriers , Revenue ,
 DENSE_RANK ()  OVER( ORDER BY Revenue DESC) AS Ranking
 FROM RevCTE


--sales from each gender along with there ranking--

;WITH GenderCTE AS
(
SELECT Product_type , Customer_Gender , SUM(Revenue_generated) 
OVER(PARTITION BY Customer_Gender) AS total_revenue
FROM [Supply chain analytics]
WHERE Customer_Gender <> 'Unknown'
)
SELECT Product_type , Customer_Gender , total_revenue ,  
DENSE_RANK ()   OVER(ORDER BY total_revenue DESC) AS ranking
FROM  GenderCTE